/*
 * Overture API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Yaksa.OrckestraCommerce.Client.Client.OpenAPIDateConverter;

namespace Yaksa.OrckestraCommerce.Client.Model
{
    /// <summary>
    /// The API used to handle saved Search queries.
    /// </summary>
    [DataContract(Name = "FindSearchQueriesRequest")]
    public partial class FindSearchQueriesRequest : IEquatable<FindSearchQueriesRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FindSearchQueriesRequest" /> class.
        /// </summary>
        /// <param name="includeQueryData">Indicates if the response should include the query data with the SearchQueries or not.</param>
        /// <param name="queryType">Query type to filter with.</param>
        public FindSearchQueriesRequest(bool includeQueryData = default(bool), string queryType = default(string))
        {
            this.IncludeQueryData = includeQueryData;
            this.QueryType = queryType;
        }

        /// <summary>
        /// Indicates if the response should include the query data with the SearchQueries or not
        /// </summary>
        /// <value>Indicates if the response should include the query data with the SearchQueries or not</value>
        [DataMember(Name = "includeQueryData", EmitDefaultValue = true)]
        public bool IncludeQueryData { get; set; }

        /// <summary>
        /// Query type to filter with
        /// </summary>
        /// <value>Query type to filter with</value>
        [DataMember(Name = "queryType", EmitDefaultValue = false)]
        public string QueryType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FindSearchQueriesRequest {\n");
            sb.Append("  IncludeQueryData: ").Append(IncludeQueryData).Append("\n");
            sb.Append("  QueryType: ").Append(QueryType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FindSearchQueriesRequest);
        }

        /// <summary>
        /// Returns true if FindSearchQueriesRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of FindSearchQueriesRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FindSearchQueriesRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IncludeQueryData == input.IncludeQueryData ||
                    this.IncludeQueryData.Equals(input.IncludeQueryData)
                ) && 
                (
                    this.QueryType == input.QueryType ||
                    (this.QueryType != null &&
                    this.QueryType.Equals(input.QueryType))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.IncludeQueryData.GetHashCode();
                if (this.QueryType != null)
                    hashCode = hashCode * 59 + this.QueryType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
