/*
 * Overture API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Yaksa.OrckestraCommerce.Client.Client.OpenAPIDateConverter;

namespace Yaksa.OrckestraCommerce.Client.Model
{
    /// <summary>
    /// FulfillmentCompetitionLocation
    /// </summary>
    [DataContract(Name = "FulfillmentCompetitionLocation")]
    public partial class FulfillmentCompetitionLocation : IEquatable<FulfillmentCompetitionLocation>, IValidatableObject
    {
        /// <summary>
        /// The status of the fulfillment competition location.
        /// </summary>
        /// <value>The status of the fulfillment competition location.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Participant for value: Participant
            /// </summary>
            [EnumMember(Value = "Participant")]
            Participant = 1,

            /// <summary>
            /// Enum Winner for value: Winner
            /// </summary>
            [EnumMember(Value = "Winner")]
            Winner = 2,

            /// <summary>
            /// Enum OptedOut for value: OptedOut
            /// </summary>
            [EnumMember(Value = "OptedOut")]
            OptedOut = 3

        }


        /// <summary>
        /// The status of the fulfillment competition location.
        /// </summary>
        /// <value>The status of the fulfillment competition location.</value>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FulfillmentCompetitionLocation" /> class.
        /// </summary>
        /// <param name="created">The date the fulfillment competition location was created..</param>
        /// <param name="createdBy">The identifier of the operator who created the fulfillment competition location..</param>
        /// <param name="fulfillmentLocationId">The identifier of the fulfillment location that is part of the competition..</param>
        /// <param name="lastModified">The date that the last modification was applied to the fulfillment competition location..</param>
        /// <param name="lastModifiedBy">The identifier of the operator who last modified the fulfillment competition location..</param>
        /// <param name="status">The status of the fulfillment competition location..</param>
        public FulfillmentCompetitionLocation(DateTime created = default(DateTime), string createdBy = default(string), string fulfillmentLocationId = default(string), DateTime lastModified = default(DateTime), string lastModifiedBy = default(string), StatusEnum? status = default(StatusEnum?))
        {
            this.Created = created;
            this.CreatedBy = createdBy;
            this.FulfillmentLocationId = fulfillmentLocationId;
            this.LastModified = lastModified;
            this.LastModifiedBy = lastModifiedBy;
            this.Status = status;
        }

        /// <summary>
        /// The date the fulfillment competition location was created.
        /// </summary>
        /// <value>The date the fulfillment competition location was created.</value>
        [DataMember(Name = "created", EmitDefaultValue = false)]
        public DateTime Created { get; set; }

        /// <summary>
        /// The identifier of the operator who created the fulfillment competition location.
        /// </summary>
        /// <value>The identifier of the operator who created the fulfillment competition location.</value>
        [DataMember(Name = "createdBy", EmitDefaultValue = false)]
        public string CreatedBy { get; set; }

        /// <summary>
        /// The identifier of the fulfillment location that is part of the competition.
        /// </summary>
        /// <value>The identifier of the fulfillment location that is part of the competition.</value>
        [DataMember(Name = "fulfillmentLocationId", EmitDefaultValue = false)]
        public string FulfillmentLocationId { get; set; }

        /// <summary>
        /// The date that the last modification was applied to the fulfillment competition location.
        /// </summary>
        /// <value>The date that the last modification was applied to the fulfillment competition location.</value>
        [DataMember(Name = "lastModified", EmitDefaultValue = false)]
        public DateTime LastModified { get; set; }

        /// <summary>
        /// The identifier of the operator who last modified the fulfillment competition location.
        /// </summary>
        /// <value>The identifier of the operator who last modified the fulfillment competition location.</value>
        [DataMember(Name = "lastModifiedBy", EmitDefaultValue = false)]
        public string LastModifiedBy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FulfillmentCompetitionLocation {\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  FulfillmentLocationId: ").Append(FulfillmentLocationId).Append("\n");
            sb.Append("  LastModified: ").Append(LastModified).Append("\n");
            sb.Append("  LastModifiedBy: ").Append(LastModifiedBy).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FulfillmentCompetitionLocation);
        }

        /// <summary>
        /// Returns true if FulfillmentCompetitionLocation instances are equal
        /// </summary>
        /// <param name="input">Instance of FulfillmentCompetitionLocation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FulfillmentCompetitionLocation input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Created == input.Created ||
                    (this.Created != null &&
                    this.Created.Equals(input.Created))
                ) && 
                (
                    this.CreatedBy == input.CreatedBy ||
                    (this.CreatedBy != null &&
                    this.CreatedBy.Equals(input.CreatedBy))
                ) && 
                (
                    this.FulfillmentLocationId == input.FulfillmentLocationId ||
                    (this.FulfillmentLocationId != null &&
                    this.FulfillmentLocationId.Equals(input.FulfillmentLocationId))
                ) && 
                (
                    this.LastModified == input.LastModified ||
                    (this.LastModified != null &&
                    this.LastModified.Equals(input.LastModified))
                ) && 
                (
                    this.LastModifiedBy == input.LastModifiedBy ||
                    (this.LastModifiedBy != null &&
                    this.LastModifiedBy.Equals(input.LastModifiedBy))
                ) && 
                (
                    this.Status == input.Status ||
                    this.Status.Equals(input.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Created != null)
                    hashCode = hashCode * 59 + this.Created.GetHashCode();
                if (this.CreatedBy != null)
                    hashCode = hashCode * 59 + this.CreatedBy.GetHashCode();
                if (this.FulfillmentLocationId != null)
                    hashCode = hashCode * 59 + this.FulfillmentLocationId.GetHashCode();
                if (this.LastModified != null)
                    hashCode = hashCode * 59 + this.LastModified.GetHashCode();
                if (this.LastModifiedBy != null)
                    hashCode = hashCode * 59 + this.LastModifiedBy.GetHashCode();
                hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
