/*
 * Overture API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Yaksa.OrckestraCommerce.Client.Client.OpenAPIDateConverter;

namespace Yaksa.OrckestraCommerce.Client.Model
{
    /// <summary>
    /// A promotion defines a set of rewards that can be applied to a Cart if a set of conditions are true.
    /// </summary>
    [DataContract(Name = "ImportCouponCodesRequest")]
    public partial class ImportCouponCodesRequest : IEquatable<ImportCouponCodesRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImportCouponCodesRequest" /> class.
        /// </summary>
        /// <param name="scopeId">The id of the requested scope.</param>
        /// <param name="correlationId">The correlation id for the durable task..</param>
        /// <param name="couponCodes">The list of coupon codes to add to the promotion.</param>
        /// <param name="promotionName">The (friendly) name of the promotion (used in messages instead of the unique id).</param>
        /// <param name="requestedBy">The user name of the request initiator.</param>
        /// <param name="taskId">The task id. Use this to query the system for the state of the task..</param>
        public ImportCouponCodesRequest(string scopeId = default(string), string correlationId = default(string), List<string> couponCodes = default(List<string>), string promotionName = default(string), string requestedBy = default(string), string taskId = default(string))
        {
            this.ScopeId = scopeId;
            this.CorrelationId = correlationId;
            this.CouponCodes = couponCodes;
            this.PromotionName = promotionName;
            this.RequestedBy = requestedBy;
            this.TaskId = taskId;
        }

        /// <summary>
        /// The id of the requested scope
        /// </summary>
        /// <value>The id of the requested scope</value>
        [DataMember(Name = "scopeId", EmitDefaultValue = false)]
        public string ScopeId { get; set; }

        /// <summary>
        /// The correlation id for the durable task.
        /// </summary>
        /// <value>The correlation id for the durable task.</value>
        [DataMember(Name = "correlationId", EmitDefaultValue = false)]
        public string CorrelationId { get; set; }

        /// <summary>
        /// The list of coupon codes to add to the promotion
        /// </summary>
        /// <value>The list of coupon codes to add to the promotion</value>
        [DataMember(Name = "couponCodes", EmitDefaultValue = false)]
        public List<string> CouponCodes { get; set; }

        /// <summary>
        /// The (friendly) name of the promotion (used in messages instead of the unique id)
        /// </summary>
        /// <value>The (friendly) name of the promotion (used in messages instead of the unique id)</value>
        [DataMember(Name = "promotionName", EmitDefaultValue = false)]
        public string PromotionName { get; set; }

        /// <summary>
        /// The user name of the request initiator
        /// </summary>
        /// <value>The user name of the request initiator</value>
        [DataMember(Name = "requestedBy", EmitDefaultValue = false)]
        public string RequestedBy { get; set; }

        /// <summary>
        /// The task id. Use this to query the system for the state of the task.
        /// </summary>
        /// <value>The task id. Use this to query the system for the state of the task.</value>
        [DataMember(Name = "taskId", EmitDefaultValue = false)]
        public string TaskId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ImportCouponCodesRequest {\n");
            sb.Append("  ScopeId: ").Append(ScopeId).Append("\n");
            sb.Append("  CorrelationId: ").Append(CorrelationId).Append("\n");
            sb.Append("  CouponCodes: ").Append(CouponCodes).Append("\n");
            sb.Append("  PromotionName: ").Append(PromotionName).Append("\n");
            sb.Append("  RequestedBy: ").Append(RequestedBy).Append("\n");
            sb.Append("  TaskId: ").Append(TaskId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ImportCouponCodesRequest);
        }

        /// <summary>
        /// Returns true if ImportCouponCodesRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ImportCouponCodesRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ImportCouponCodesRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ScopeId == input.ScopeId ||
                    (this.ScopeId != null &&
                    this.ScopeId.Equals(input.ScopeId))
                ) && 
                (
                    this.CorrelationId == input.CorrelationId ||
                    (this.CorrelationId != null &&
                    this.CorrelationId.Equals(input.CorrelationId))
                ) && 
                (
                    this.CouponCodes == input.CouponCodes ||
                    this.CouponCodes != null &&
                    input.CouponCodes != null &&
                    this.CouponCodes.SequenceEqual(input.CouponCodes)
                ) && 
                (
                    this.PromotionName == input.PromotionName ||
                    (this.PromotionName != null &&
                    this.PromotionName.Equals(input.PromotionName))
                ) && 
                (
                    this.RequestedBy == input.RequestedBy ||
                    (this.RequestedBy != null &&
                    this.RequestedBy.Equals(input.RequestedBy))
                ) && 
                (
                    this.TaskId == input.TaskId ||
                    (this.TaskId != null &&
                    this.TaskId.Equals(input.TaskId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ScopeId != null)
                    hashCode = hashCode * 59 + this.ScopeId.GetHashCode();
                if (this.CorrelationId != null)
                    hashCode = hashCode * 59 + this.CorrelationId.GetHashCode();
                if (this.CouponCodes != null)
                    hashCode = hashCode * 59 + this.CouponCodes.GetHashCode();
                if (this.PromotionName != null)
                    hashCode = hashCode * 59 + this.PromotionName.GetHashCode();
                if (this.RequestedBy != null)
                    hashCode = hashCode * 59 + this.RequestedBy.GetHashCode();
                if (this.TaskId != null)
                    hashCode = hashCode * 59 + this.TaskId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
