/*
 * Overture API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Yaksa.OrckestraCommerce.Client.Client.OpenAPIDateConverter;

namespace Yaksa.OrckestraCommerce.Client.Model
{
    /// <summary>
    /// PaymentProviderInfo
    /// </summary>
    [DataContract(Name = "PaymentProviderInfo")]
    public partial class PaymentProviderInfo : IEquatable<PaymentProviderInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentProviderInfo" /> class.
        /// </summary>
        /// <param name="description">the description for this provider.</param>
        /// <param name="displayName">displayName.</param>
        /// <param name="id">the unique identifier for this provider.</param>
        /// <param name="implementationTypeName">the implementation type name of this provider.</param>
        /// <param name="isActive">a value indicating whether this provider is currently enabled and can be used.</param>
        /// <param name="isDefaultPaymentMethodSupported">a value indicating whether default payment method is supported for the payment provider.</param>
        /// <param name="isRefreshOperationSupported">a value indicating whether refresh operation is supported.</param>
        /// <param name="name">the name for this provider.</param>
        /// <param name="supportedCultureIds">the supported culture ids.</param>
        /// <param name="supportedCurrencyIds">the supported currency ids.</param>
        /// <param name="supportedPaymentMethodTypeIds">the supported PaymentMethodTypeIds.</param>
        public PaymentProviderInfo(string description = default(string), Dictionary<string, string> displayName = default(Dictionary<string, string>), string id = default(string), string implementationTypeName = default(string), bool isActive = default(bool), bool isDefaultPaymentMethodSupported = default(bool), bool isRefreshOperationSupported = default(bool), string name = default(string), string supportedCultureIds = default(string), string supportedCurrencyIds = default(string), string supportedPaymentMethodTypeIds = default(string))
        {
            this.Description = description;
            this.DisplayName = displayName;
            this.Id = id;
            this.ImplementationTypeName = implementationTypeName;
            this.IsActive = isActive;
            this.IsDefaultPaymentMethodSupported = isDefaultPaymentMethodSupported;
            this.IsRefreshOperationSupported = isRefreshOperationSupported;
            this.Name = name;
            this.SupportedCultureIds = supportedCultureIds;
            this.SupportedCurrencyIds = supportedCurrencyIds;
            this.SupportedPaymentMethodTypeIds = supportedPaymentMethodTypeIds;
        }

        /// <summary>
        /// the description for this provider
        /// </summary>
        /// <value>the description for this provider</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [DataMember(Name = "displayName", EmitDefaultValue = false)]
        public Dictionary<string, string> DisplayName { get; set; }

        /// <summary>
        /// the unique identifier for this provider
        /// </summary>
        /// <value>the unique identifier for this provider</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// the implementation type name of this provider
        /// </summary>
        /// <value>the implementation type name of this provider</value>
        [DataMember(Name = "implementationTypeName", EmitDefaultValue = false)]
        public string ImplementationTypeName { get; set; }

        /// <summary>
        /// a value indicating whether this provider is currently enabled and can be used
        /// </summary>
        /// <value>a value indicating whether this provider is currently enabled and can be used</value>
        [DataMember(Name = "isActive", EmitDefaultValue = true)]
        public bool IsActive { get; set; }

        /// <summary>
        /// a value indicating whether default payment method is supported for the payment provider
        /// </summary>
        /// <value>a value indicating whether default payment method is supported for the payment provider</value>
        [DataMember(Name = "isDefaultPaymentMethodSupported", EmitDefaultValue = true)]
        public bool IsDefaultPaymentMethodSupported { get; set; }

        /// <summary>
        /// a value indicating whether refresh operation is supported
        /// </summary>
        /// <value>a value indicating whether refresh operation is supported</value>
        [DataMember(Name = "isRefreshOperationSupported", EmitDefaultValue = true)]
        public bool IsRefreshOperationSupported { get; set; }

        /// <summary>
        /// the name for this provider
        /// </summary>
        /// <value>the name for this provider</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// the supported culture ids
        /// </summary>
        /// <value>the supported culture ids</value>
        [DataMember(Name = "supportedCultureIds", EmitDefaultValue = false)]
        public string SupportedCultureIds { get; set; }

        /// <summary>
        /// the supported currency ids
        /// </summary>
        /// <value>the supported currency ids</value>
        [DataMember(Name = "supportedCurrencyIds", EmitDefaultValue = false)]
        public string SupportedCurrencyIds { get; set; }

        /// <summary>
        /// the supported PaymentMethodTypeIds
        /// </summary>
        /// <value>the supported PaymentMethodTypeIds</value>
        [DataMember(Name = "supportedPaymentMethodTypeIds", EmitDefaultValue = false)]
        public string SupportedPaymentMethodTypeIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentProviderInfo {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ImplementationTypeName: ").Append(ImplementationTypeName).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  IsDefaultPaymentMethodSupported: ").Append(IsDefaultPaymentMethodSupported).Append("\n");
            sb.Append("  IsRefreshOperationSupported: ").Append(IsRefreshOperationSupported).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  SupportedCultureIds: ").Append(SupportedCultureIds).Append("\n");
            sb.Append("  SupportedCurrencyIds: ").Append(SupportedCurrencyIds).Append("\n");
            sb.Append("  SupportedPaymentMethodTypeIds: ").Append(SupportedPaymentMethodTypeIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaymentProviderInfo);
        }

        /// <summary>
        /// Returns true if PaymentProviderInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of PaymentProviderInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentProviderInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.DisplayName == input.DisplayName ||
                    this.DisplayName != null &&
                    input.DisplayName != null &&
                    this.DisplayName.SequenceEqual(input.DisplayName)
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.ImplementationTypeName == input.ImplementationTypeName ||
                    (this.ImplementationTypeName != null &&
                    this.ImplementationTypeName.Equals(input.ImplementationTypeName))
                ) && 
                (
                    this.IsActive == input.IsActive ||
                    this.IsActive.Equals(input.IsActive)
                ) && 
                (
                    this.IsDefaultPaymentMethodSupported == input.IsDefaultPaymentMethodSupported ||
                    this.IsDefaultPaymentMethodSupported.Equals(input.IsDefaultPaymentMethodSupported)
                ) && 
                (
                    this.IsRefreshOperationSupported == input.IsRefreshOperationSupported ||
                    this.IsRefreshOperationSupported.Equals(input.IsRefreshOperationSupported)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.SupportedCultureIds == input.SupportedCultureIds ||
                    (this.SupportedCultureIds != null &&
                    this.SupportedCultureIds.Equals(input.SupportedCultureIds))
                ) && 
                (
                    this.SupportedCurrencyIds == input.SupportedCurrencyIds ||
                    (this.SupportedCurrencyIds != null &&
                    this.SupportedCurrencyIds.Equals(input.SupportedCurrencyIds))
                ) && 
                (
                    this.SupportedPaymentMethodTypeIds == input.SupportedPaymentMethodTypeIds ||
                    (this.SupportedPaymentMethodTypeIds != null &&
                    this.SupportedPaymentMethodTypeIds.Equals(input.SupportedPaymentMethodTypeIds))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.DisplayName != null)
                    hashCode = hashCode * 59 + this.DisplayName.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.ImplementationTypeName != null)
                    hashCode = hashCode * 59 + this.ImplementationTypeName.GetHashCode();
                hashCode = hashCode * 59 + this.IsActive.GetHashCode();
                hashCode = hashCode * 59 + this.IsDefaultPaymentMethodSupported.GetHashCode();
                hashCode = hashCode * 59 + this.IsRefreshOperationSupported.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.SupportedCultureIds != null)
                    hashCode = hashCode * 59 + this.SupportedCultureIds.GetHashCode();
                if (this.SupportedCurrencyIds != null)
                    hashCode = hashCode * 59 + this.SupportedCurrencyIds.GetHashCode();
                if (this.SupportedPaymentMethodTypeIds != null)
                    hashCode = hashCode * 59 + this.SupportedPaymentMethodTypeIds.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
