/*
 * Overture API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Yaksa.OrckestraCommerce.Client.Client.OpenAPIDateConverter;

namespace Yaksa.OrckestraCommerce.Client.Model
{
    /// <summary>
    /// RenderOrderShipmentTemplateResponse
    /// </summary>
    [DataContract(Name = "RenderOrderShipmentTemplateResponse")]
    public partial class RenderOrderShipmentTemplateResponse : IEquatable<RenderOrderShipmentTemplateResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RenderOrderShipmentTemplateResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RenderOrderShipmentTemplateResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RenderOrderShipmentTemplateResponse" /> class.
        /// </summary>
        /// <param name="content">the rendered template..</param>
        /// <param name="cultureName">The name of the culture (language) to used to render the template. (required).</param>
        /// <param name="orderId">the id of the order associated to the shipment..</param>
        /// <param name="scopeId">the scope of the shipment..</param>
        /// <param name="shipmentId">the id of the associated shipment..</param>
        public RenderOrderShipmentTemplateResponse(string content = default(string), string cultureName = default(string), string orderId = default(string), string scopeId = default(string), string shipmentId = default(string))
        {
            // to ensure "cultureName" is required (not null)
            this.CultureName = cultureName ?? throw new ArgumentNullException("cultureName is a required property for RenderOrderShipmentTemplateResponse and cannot be null");
            this.Content = content;
            this.OrderId = orderId;
            this.ScopeId = scopeId;
            this.ShipmentId = shipmentId;
        }

        /// <summary>
        /// the rendered template.
        /// </summary>
        /// <value>the rendered template.</value>
        [DataMember(Name = "content", EmitDefaultValue = false)]
        public string Content { get; set; }

        /// <summary>
        /// The name of the culture (language) to used to render the template.
        /// </summary>
        /// <value>The name of the culture (language) to used to render the template.</value>
        [DataMember(Name = "cultureName", IsRequired = true, EmitDefaultValue = false)]
        public string CultureName { get; set; }

        /// <summary>
        /// the id of the order associated to the shipment.
        /// </summary>
        /// <value>the id of the order associated to the shipment.</value>
        [DataMember(Name = "orderId", EmitDefaultValue = false)]
        public string OrderId { get; set; }

        /// <summary>
        /// the scope of the shipment.
        /// </summary>
        /// <value>the scope of the shipment.</value>
        [DataMember(Name = "scopeId", EmitDefaultValue = false)]
        public string ScopeId { get; set; }

        /// <summary>
        /// the id of the associated shipment.
        /// </summary>
        /// <value>the id of the associated shipment.</value>
        [DataMember(Name = "shipmentId", EmitDefaultValue = false)]
        public string ShipmentId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RenderOrderShipmentTemplateResponse {\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  CultureName: ").Append(CultureName).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  ScopeId: ").Append(ScopeId).Append("\n");
            sb.Append("  ShipmentId: ").Append(ShipmentId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RenderOrderShipmentTemplateResponse);
        }

        /// <summary>
        /// Returns true if RenderOrderShipmentTemplateResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of RenderOrderShipmentTemplateResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RenderOrderShipmentTemplateResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Content == input.Content ||
                    (this.Content != null &&
                    this.Content.Equals(input.Content))
                ) && 
                (
                    this.CultureName == input.CultureName ||
                    (this.CultureName != null &&
                    this.CultureName.Equals(input.CultureName))
                ) && 
                (
                    this.OrderId == input.OrderId ||
                    (this.OrderId != null &&
                    this.OrderId.Equals(input.OrderId))
                ) && 
                (
                    this.ScopeId == input.ScopeId ||
                    (this.ScopeId != null &&
                    this.ScopeId.Equals(input.ScopeId))
                ) && 
                (
                    this.ShipmentId == input.ShipmentId ||
                    (this.ShipmentId != null &&
                    this.ShipmentId.Equals(input.ShipmentId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Content != null)
                    hashCode = hashCode * 59 + this.Content.GetHashCode();
                if (this.CultureName != null)
                    hashCode = hashCode * 59 + this.CultureName.GetHashCode();
                if (this.OrderId != null)
                    hashCode = hashCode * 59 + this.OrderId.GetHashCode();
                if (this.ScopeId != null)
                    hashCode = hashCode * 59 + this.ScopeId.GetHashCode();
                if (this.ShipmentId != null)
                    hashCode = hashCode * 59 + this.ShipmentId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
