/*
 * Overture API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Yaksa.OrckestraCommerce.Client.Client;
using Yaksa.OrckestraCommerce.Client.Model;

namespace Yaksa.OrckestraCommerce.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFulfillmentMethodsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Retrieve the list of all the potential FulfillmentMethod of a given customer Cart - {FindCalculatedFulfillmentMethodsRequest}
        /// </summary>
        /// <remarks>
        /// Retrieve the list of all the potential FulfillmentMethod of a given customer Cart
        /// </remarks>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <param name="customerId">the unique identifier of the Customer owning the cart.</param>
        /// <param name="cartName">The name of the cart to retrieve.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>List&lt;FulfillmentMethod&gt;</returns>
        List<FulfillmentMethod> FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePost(string accept, string scopeId, string customerId, string cartName, FindCalculatedFulfillmentMethodsRequest body = default(FindCalculatedFulfillmentMethodsRequest));

        /// <summary>
        /// Retrieve the list of all the potential FulfillmentMethod of a given customer Cart - {FindCalculatedFulfillmentMethodsRequest}
        /// </summary>
        /// <remarks>
        /// Retrieve the list of all the potential FulfillmentMethod of a given customer Cart
        /// </remarks>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <param name="customerId">the unique identifier of the Customer owning the cart.</param>
        /// <param name="cartName">The name of the cart to retrieve.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of List&lt;FulfillmentMethod&gt;</returns>
        ApiResponse<List<FulfillmentMethod>> FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePostWithHttpInfo(string accept, string scopeId, string customerId, string cartName, FindCalculatedFulfillmentMethodsRequest body = default(FindCalculatedFulfillmentMethodsRequest));
        /// <summary>
        /// Gets the list of all the available fulfillment methods for a given scope - {GetAvailableFulfillmentMethodsByScopeRequest}
        /// </summary>
        /// <remarks>
        /// Gets the list of all the available fulfillment methods for a given scope
        /// </remarks>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <returns>GetFulfillmentMethodsResponse</returns>
        GetFulfillmentMethodsResponse GetAvailableFulfillmentMethodsByScopeRequestScopeIdGet(string accept, string scopeId);

        /// <summary>
        /// Gets the list of all the available fulfillment methods for a given scope - {GetAvailableFulfillmentMethodsByScopeRequest}
        /// </summary>
        /// <remarks>
        /// Gets the list of all the available fulfillment methods for a given scope
        /// </remarks>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <returns>ApiResponse of GetFulfillmentMethodsResponse</returns>
        ApiResponse<GetFulfillmentMethodsResponse> GetAvailableFulfillmentMethodsByScopeRequestScopeIdGetWithHttpInfo(string accept, string scopeId);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFulfillmentMethodsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Retrieve the list of all the potential FulfillmentMethod of a given customer Cart - {FindCalculatedFulfillmentMethodsRequest}
        /// </summary>
        /// <remarks>
        /// Retrieve the list of all the potential FulfillmentMethod of a given customer Cart
        /// </remarks>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <param name="customerId">the unique identifier of the Customer owning the cart.</param>
        /// <param name="cartName">The name of the cart to retrieve.</param>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;FulfillmentMethod&gt;</returns>
        System.Threading.Tasks.Task<List<FulfillmentMethod>> FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePostAsync(string accept, string scopeId, string customerId, string cartName, FindCalculatedFulfillmentMethodsRequest body = default(FindCalculatedFulfillmentMethodsRequest), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Retrieve the list of all the potential FulfillmentMethod of a given customer Cart - {FindCalculatedFulfillmentMethodsRequest}
        /// </summary>
        /// <remarks>
        /// Retrieve the list of all the potential FulfillmentMethod of a given customer Cart
        /// </remarks>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <param name="customerId">the unique identifier of the Customer owning the cart.</param>
        /// <param name="cartName">The name of the cart to retrieve.</param>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;FulfillmentMethod&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<FulfillmentMethod>>> FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePostWithHttpInfoAsync(string accept, string scopeId, string customerId, string cartName, FindCalculatedFulfillmentMethodsRequest body = default(FindCalculatedFulfillmentMethodsRequest), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Gets the list of all the available fulfillment methods for a given scope - {GetAvailableFulfillmentMethodsByScopeRequest}
        /// </summary>
        /// <remarks>
        /// Gets the list of all the available fulfillment methods for a given scope
        /// </remarks>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetFulfillmentMethodsResponse</returns>
        System.Threading.Tasks.Task<GetFulfillmentMethodsResponse> GetAvailableFulfillmentMethodsByScopeRequestScopeIdGetAsync(string accept, string scopeId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Gets the list of all the available fulfillment methods for a given scope - {GetAvailableFulfillmentMethodsByScopeRequest}
        /// </summary>
        /// <remarks>
        /// Gets the list of all the available fulfillment methods for a given scope
        /// </remarks>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetFulfillmentMethodsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetFulfillmentMethodsResponse>> GetAvailableFulfillmentMethodsByScopeRequestScopeIdGetWithHttpInfoAsync(string accept, string scopeId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFulfillmentMethodsApi : IFulfillmentMethodsApiSync, IFulfillmentMethodsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FulfillmentMethodsApi : IFulfillmentMethodsApi
    {
        private Yaksa.OrckestraCommerce.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FulfillmentMethodsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FulfillmentMethodsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FulfillmentMethodsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FulfillmentMethodsApi(String basePath)
        {
            this.Configuration = Yaksa.OrckestraCommerce.Client.Client.Configuration.MergeConfigurations(
                Yaksa.OrckestraCommerce.Client.Client.GlobalConfiguration.Instance,
                new Yaksa.OrckestraCommerce.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Yaksa.OrckestraCommerce.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Yaksa.OrckestraCommerce.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Yaksa.OrckestraCommerce.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FulfillmentMethodsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public FulfillmentMethodsApi(Yaksa.OrckestraCommerce.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Yaksa.OrckestraCommerce.Client.Client.Configuration.MergeConfigurations(
                Yaksa.OrckestraCommerce.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Yaksa.OrckestraCommerce.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Yaksa.OrckestraCommerce.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Yaksa.OrckestraCommerce.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FulfillmentMethodsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public FulfillmentMethodsApi(Yaksa.OrckestraCommerce.Client.Client.ISynchronousClient client, Yaksa.OrckestraCommerce.Client.Client.IAsynchronousClient asyncClient, Yaksa.OrckestraCommerce.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Yaksa.OrckestraCommerce.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Yaksa.OrckestraCommerce.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Yaksa.OrckestraCommerce.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Yaksa.OrckestraCommerce.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Yaksa.OrckestraCommerce.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Retrieve the list of all the potential FulfillmentMethod of a given customer Cart - {FindCalculatedFulfillmentMethodsRequest} Retrieve the list of all the potential FulfillmentMethod of a given customer Cart
        /// </summary>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <param name="customerId">the unique identifier of the Customer owning the cart.</param>
        /// <param name="cartName">The name of the cart to retrieve.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>List&lt;FulfillmentMethod&gt;</returns>
        public List<FulfillmentMethod> FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePost(string accept, string scopeId, string customerId, string cartName, FindCalculatedFulfillmentMethodsRequest body = default(FindCalculatedFulfillmentMethodsRequest))
        {
            Yaksa.OrckestraCommerce.Client.Client.ApiResponse<List<FulfillmentMethod>> localVarResponse = FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePostWithHttpInfo(accept, scopeId, customerId, cartName, body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve the list of all the potential FulfillmentMethod of a given customer Cart - {FindCalculatedFulfillmentMethodsRequest} Retrieve the list of all the potential FulfillmentMethod of a given customer Cart
        /// </summary>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <param name="customerId">the unique identifier of the Customer owning the cart.</param>
        /// <param name="cartName">The name of the cart to retrieve.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of List&lt;FulfillmentMethod&gt;</returns>
        public Yaksa.OrckestraCommerce.Client.Client.ApiResponse<List<FulfillmentMethod>> FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePostWithHttpInfo(string accept, string scopeId, string customerId, string cartName, FindCalculatedFulfillmentMethodsRequest body = default(FindCalculatedFulfillmentMethodsRequest))
        {
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new Yaksa.OrckestraCommerce.Client.Client.ApiException(400, "Missing required parameter 'accept' when calling FulfillmentMethodsApi->FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePost");

            // verify the required parameter 'scopeId' is set
            if (scopeId == null)
                throw new Yaksa.OrckestraCommerce.Client.Client.ApiException(400, "Missing required parameter 'scopeId' when calling FulfillmentMethodsApi->FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePost");

            // verify the required parameter 'customerId' is set
            if (customerId == null)
                throw new Yaksa.OrckestraCommerce.Client.Client.ApiException(400, "Missing required parameter 'customerId' when calling FulfillmentMethodsApi->FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePost");

            // verify the required parameter 'cartName' is set
            if (cartName == null)
                throw new Yaksa.OrckestraCommerce.Client.Client.ApiException(400, "Missing required parameter 'cartName' when calling FulfillmentMethodsApi->FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePost");

            Yaksa.OrckestraCommerce.Client.Client.RequestOptions localVarRequestOptions = new Yaksa.OrckestraCommerce.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Yaksa.OrckestraCommerce.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Yaksa.OrckestraCommerce.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("ScopeId", Yaksa.OrckestraCommerce.Client.Client.ClientUtils.ParameterToString(scopeId)); // path parameter
            localVarRequestOptions.PathParameters.Add("CustomerId", Yaksa.OrckestraCommerce.Client.Client.ClientUtils.ParameterToString(customerId)); // path parameter
            localVarRequestOptions.PathParameters.Add("CartName", Yaksa.OrckestraCommerce.Client.Client.ClientUtils.ParameterToString(cartName)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("Accept", Yaksa.OrckestraCommerce.Client.Client.ClientUtils.ParameterToString(accept)); // header parameter
            localVarRequestOptions.Data = body;


            // make the HTTP request
            var localVarResponse = this.Client.Post<List<FulfillmentMethod>>("/fulfillmentMethods/{ScopeId}/{CustomerId}/{CartName}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve the list of all the potential FulfillmentMethod of a given customer Cart - {FindCalculatedFulfillmentMethodsRequest} Retrieve the list of all the potential FulfillmentMethod of a given customer Cart
        /// </summary>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <param name="customerId">the unique identifier of the Customer owning the cart.</param>
        /// <param name="cartName">The name of the cart to retrieve.</param>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;FulfillmentMethod&gt;</returns>
        public async System.Threading.Tasks.Task<List<FulfillmentMethod>> FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePostAsync(string accept, string scopeId, string customerId, string cartName, FindCalculatedFulfillmentMethodsRequest body = default(FindCalculatedFulfillmentMethodsRequest), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Yaksa.OrckestraCommerce.Client.Client.ApiResponse<List<FulfillmentMethod>> localVarResponse = await FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePostWithHttpInfoAsync(accept, scopeId, customerId, cartName, body, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve the list of all the potential FulfillmentMethod of a given customer Cart - {FindCalculatedFulfillmentMethodsRequest} Retrieve the list of all the potential FulfillmentMethod of a given customer Cart
        /// </summary>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <param name="customerId">the unique identifier of the Customer owning the cart.</param>
        /// <param name="cartName">The name of the cart to retrieve.</param>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;FulfillmentMethod&gt;)</returns>
        public async System.Threading.Tasks.Task<Yaksa.OrckestraCommerce.Client.Client.ApiResponse<List<FulfillmentMethod>>> FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePostWithHttpInfoAsync(string accept, string scopeId, string customerId, string cartName, FindCalculatedFulfillmentMethodsRequest body = default(FindCalculatedFulfillmentMethodsRequest), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new Yaksa.OrckestraCommerce.Client.Client.ApiException(400, "Missing required parameter 'accept' when calling FulfillmentMethodsApi->FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePost");

            // verify the required parameter 'scopeId' is set
            if (scopeId == null)
                throw new Yaksa.OrckestraCommerce.Client.Client.ApiException(400, "Missing required parameter 'scopeId' when calling FulfillmentMethodsApi->FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePost");

            // verify the required parameter 'customerId' is set
            if (customerId == null)
                throw new Yaksa.OrckestraCommerce.Client.Client.ApiException(400, "Missing required parameter 'customerId' when calling FulfillmentMethodsApi->FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePost");

            // verify the required parameter 'cartName' is set
            if (cartName == null)
                throw new Yaksa.OrckestraCommerce.Client.Client.ApiException(400, "Missing required parameter 'cartName' when calling FulfillmentMethodsApi->FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePost");


            Yaksa.OrckestraCommerce.Client.Client.RequestOptions localVarRequestOptions = new Yaksa.OrckestraCommerce.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Yaksa.OrckestraCommerce.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Yaksa.OrckestraCommerce.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("ScopeId", Yaksa.OrckestraCommerce.Client.Client.ClientUtils.ParameterToString(scopeId)); // path parameter
            localVarRequestOptions.PathParameters.Add("CustomerId", Yaksa.OrckestraCommerce.Client.Client.ClientUtils.ParameterToString(customerId)); // path parameter
            localVarRequestOptions.PathParameters.Add("CartName", Yaksa.OrckestraCommerce.Client.Client.ClientUtils.ParameterToString(cartName)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("Accept", Yaksa.OrckestraCommerce.Client.Client.ClientUtils.ParameterToString(accept)); // header parameter
            localVarRequestOptions.Data = body;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<List<FulfillmentMethod>>("/fulfillmentMethods/{ScopeId}/{CustomerId}/{CartName}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindCalculatedFulfillmentMethodsRequestScopeIdCustomerIdCartNamePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets the list of all the available fulfillment methods for a given scope - {GetAvailableFulfillmentMethodsByScopeRequest} Gets the list of all the available fulfillment methods for a given scope
        /// </summary>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <returns>GetFulfillmentMethodsResponse</returns>
        public GetFulfillmentMethodsResponse GetAvailableFulfillmentMethodsByScopeRequestScopeIdGet(string accept, string scopeId)
        {
            Yaksa.OrckestraCommerce.Client.Client.ApiResponse<GetFulfillmentMethodsResponse> localVarResponse = GetAvailableFulfillmentMethodsByScopeRequestScopeIdGetWithHttpInfo(accept, scopeId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the list of all the available fulfillment methods for a given scope - {GetAvailableFulfillmentMethodsByScopeRequest} Gets the list of all the available fulfillment methods for a given scope
        /// </summary>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <returns>ApiResponse of GetFulfillmentMethodsResponse</returns>
        public Yaksa.OrckestraCommerce.Client.Client.ApiResponse<GetFulfillmentMethodsResponse> GetAvailableFulfillmentMethodsByScopeRequestScopeIdGetWithHttpInfo(string accept, string scopeId)
        {
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new Yaksa.OrckestraCommerce.Client.Client.ApiException(400, "Missing required parameter 'accept' when calling FulfillmentMethodsApi->GetAvailableFulfillmentMethodsByScopeRequestScopeIdGet");

            // verify the required parameter 'scopeId' is set
            if (scopeId == null)
                throw new Yaksa.OrckestraCommerce.Client.Client.ApiException(400, "Missing required parameter 'scopeId' when calling FulfillmentMethodsApi->GetAvailableFulfillmentMethodsByScopeRequestScopeIdGet");

            Yaksa.OrckestraCommerce.Client.Client.RequestOptions localVarRequestOptions = new Yaksa.OrckestraCommerce.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Yaksa.OrckestraCommerce.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Yaksa.OrckestraCommerce.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("ScopeId", Yaksa.OrckestraCommerce.Client.Client.ClientUtils.ParameterToString(scopeId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("Accept", Yaksa.OrckestraCommerce.Client.Client.ClientUtils.ParameterToString(accept)); // header parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<GetFulfillmentMethodsResponse>("/fulfillmentMethods/{ScopeId}/", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAvailableFulfillmentMethodsByScopeRequestScopeIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets the list of all the available fulfillment methods for a given scope - {GetAvailableFulfillmentMethodsByScopeRequest} Gets the list of all the available fulfillment methods for a given scope
        /// </summary>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetFulfillmentMethodsResponse</returns>
        public async System.Threading.Tasks.Task<GetFulfillmentMethodsResponse> GetAvailableFulfillmentMethodsByScopeRequestScopeIdGetAsync(string accept, string scopeId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Yaksa.OrckestraCommerce.Client.Client.ApiResponse<GetFulfillmentMethodsResponse> localVarResponse = await GetAvailableFulfillmentMethodsByScopeRequestScopeIdGetWithHttpInfoAsync(accept, scopeId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the list of all the available fulfillment methods for a given scope - {GetAvailableFulfillmentMethodsByScopeRequest} Gets the list of all the available fulfillment methods for a given scope
        /// </summary>
        /// <exception cref="Yaksa.OrckestraCommerce.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accept">Accept Header</param>
        /// <param name="scopeId">The id of the requested scope</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetFulfillmentMethodsResponse)</returns>
        public async System.Threading.Tasks.Task<Yaksa.OrckestraCommerce.Client.Client.ApiResponse<GetFulfillmentMethodsResponse>> GetAvailableFulfillmentMethodsByScopeRequestScopeIdGetWithHttpInfoAsync(string accept, string scopeId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new Yaksa.OrckestraCommerce.Client.Client.ApiException(400, "Missing required parameter 'accept' when calling FulfillmentMethodsApi->GetAvailableFulfillmentMethodsByScopeRequestScopeIdGet");

            // verify the required parameter 'scopeId' is set
            if (scopeId == null)
                throw new Yaksa.OrckestraCommerce.Client.Client.ApiException(400, "Missing required parameter 'scopeId' when calling FulfillmentMethodsApi->GetAvailableFulfillmentMethodsByScopeRequestScopeIdGet");


            Yaksa.OrckestraCommerce.Client.Client.RequestOptions localVarRequestOptions = new Yaksa.OrckestraCommerce.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Yaksa.OrckestraCommerce.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Yaksa.OrckestraCommerce.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("ScopeId", Yaksa.OrckestraCommerce.Client.Client.ClientUtils.ParameterToString(scopeId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("Accept", Yaksa.OrckestraCommerce.Client.Client.ClientUtils.ParameterToString(accept)); // header parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetFulfillmentMethodsResponse>("/fulfillmentMethods/{ScopeId}/", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAvailableFulfillmentMethodsByScopeRequestScopeIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
